ccbs:
  bp01:
    bp01f0003:
      rpt-code: BP220RPT
      filename: BP220RPT_T%s.csv
      years:
        shift: -2
      group-bill-items:
        - name: 全業務逾期１個月欠費
          pattern: .*
          bill-item-types:
            - name: 未收回應收帳款
              type: .*
            - name:
              type:
        - name: 行動業務逾期１個月欠費
          pattern: G[1|2]
          bill-item-types:
            - name: 行動欠費
              type: G1
            - name: 手機賠償費
              type: G2
        - name: 光世代業務逾期１個月欠費
          pattern: L[1|2]
          bill-item-types:
            - name: 光世代
              type: L1
            - name: ＶＴＵＲ欠費
              type: L2
        - name: ＭＯＤ業務逾期１個月欠費
          pattern: M[1|2]
          bill-item-types:
            - name: ＭＯＤ
              type: M1
            - name: 機上盒欠費
              type: M2
        - name: GOOGLE業務逾期１個月欠費
          pattern: A1
          bill-item-types:
            - name: 未收回應收帳款
              type: A1
            - name:
              type:
        - name: APPLE業務逾期１個月欠費
          pattern: B1
          bill-item-types:
            - name: 未收回應收帳款
              type: B1
            - name:
              type:
        - name: Netflix業務逾期１個月欠費
          pattern: C1
          bill-item-types:
            - name: 未收回應收帳款
              type: C1
            - name:
              type:
      rpt-cust-types:
        - name: 一般客戶
          type: 1
        - name: 中小企業客戶
          type: 2
        - name: 大企業客戶
          type: 3

    bp01f0013:
      rpt-code: BP2230D2
      filename: BP2230D2_T%s.csv
      years:
        shift: -1
      titles:
        [
          1144應收帳款,
          1144應收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
          1812催收帳款,
        ]

    bp01f0015:
      rpt-code: BP2230D6
      filename: BP2230D6_T%s.csv

    rqbp019:
      input: ${ccbs.bpgsm010Input:/workspaces/ccbs/chtreport/out/in/bpgsm010}
      type-configs:
        - name: MBMS
          pattern: BPGSM010_(.*)\.TXT
          output: ${ccbs.txtFilePath:/workspaces/ccbs/chtreport/out/txt/}
          filename: BPGSM010_%s%s%s.TXT
        - name: CCBS
          pattern: BPGSM010_(.*)\.TXT
          output: ${ccbs.csvFilePath:/workspaces/ccbs/chtreport/out/txt/}
          filename: BPGSM010_%s%s%s.TXT
        - name: BPGNERP
          output: ${ccbs.txtFilePath:/workspaces/ccbs/chtreport/out/txt/}
          filename: BPGSM010_SCAN_BPGNERP_%s%s.TXT
