ccbs:
  bp01:
    bp01f0003:
      rpt-code: BP220RPT
      filename: BP220RPT_T%s.csv
      group-bill-items:
        - name: 全業務逾期１個月欠費
          pattern: .*
          bill-item-types:
            - name: 未收回應收帳款
              type: .*
            - name: 
              type: 
        - name: 行動業務逾期１個月欠費
          pattern: G[1|2]
          bill-item-types:
            - name: 行動欠費
              type: G1
            - name: 手機賠償費
              type: G2
        - name: 光世代業務逾期１個月欠費
          pattern: L[1|2]
          bill-item-types:
            - name: 光世代
              type: L1
            - name: ＶＴＵＲ欠費
              type: L2
        - name: ＭＯＤ業務逾期１個月欠費
          pattern: M[1|2]
          bill-item-types:
            - name: ＭＯＤ
              type: M1
            - name: 機上盒欠費
              type: M2
        - name: GOOGLE業務逾期１個月欠費
          pattern: A1
          bill-item-types:
            - name: 未收回應收帳款
              type: A1
            - name: 
              type: 
        - name: APPLE業務逾期１個月欠費
          pattern: B1
          bill-item-types:
            - name: 未收回應收帳款
              type: B1
            - name: 
              type: 
        - name: Netflix業務逾期１個月欠費
          pattern: C1
          bill-item-types:
            - name: 未收回應收帳款
              type: C1
            - name: 
              type: 
      rpt-cust-types:
        - name: 一般客戶
          type: 1
        - name: 中小企業客戶
          type: 2
        - name: 大企業客戶
          type: 3

    bp01f0007:
      rpt-code: BPGSM010
      filename: BPGSM010_%s%s%s.TXT
      file-source: /workspaces/ccbs/chtccbs/out/in/bpgsm010
      file-pattern-1: BPGSM010_MBMS_\d*\.TXT
      file-pattern-2: BPGSM010_CCBS_\d*\.TXT

    bp01f0013:
      rpt-code: BP2230D2
      filename: BP2230D2_%s.csv
      years:
        start: 1
        titles: [1144應收帳款,1144應收帳款,1812催收帳款,1812催收帳款,1812催收帳款,1812催收帳款,1812催收帳款,
          1812催收帳款,1812催收帳款,1812催收帳款,1812催收帳款,1812催收帳款,1812催收帳款]
   
    bp01f0015:
      rpt-code: BP2230D6
      filename: BP2230D6_T%s.csv
      years:
        start: 0
        length: 6
      receive-items:
        headers: "應收帳款,加,催收款項,"
        receive-types:
          - name: 1144-02H,+,1812-02H,應收銷貨收入 ( 語意雲健康雲 ) 
            type: '[1144\-02H|1812\-02H]'
          - name: 1144-11N,+,1812-11N,應收市內網路業務收入 
            type: '[1144\-11N|1812\-11N]'
          - name: 1144-16N,+,1812-16N,應收ＭＯＤ業務收入－收據類 
            type: '[1144\-16N|1812\-16N]'
          - name: 1144-17N,+,1812-17N,應收ＭＯＤ業務收入－發票類 
            type: '[1144\-17N|1812\-17N]'
          - name: 1144-21N,+,1812-21N,應收長途網路業務收入 
            type: '[1144\-21N|1812\-21N]'
          - name: 1144-31N,+,1812-31N,應收國際網路業務收入 
            type: '[1144\-31N|1812\-31N]'
          - name: 1144-41N,+,1812-41N,應收ＧＳＭ行動電話業務收入 
            type: '[1144\-41N|1812\-41N]'
          - name: 1144-42N,+,1812-42N,應收３Ｇ行動電話業務收入 
            type: '[1144\-42N|1812\-42N]'
          - name: 1144-45N,+,1812-45N,應收４Ｇ行動電話業務收入 
            type: '[1144\-45N|1812\-45N]'
          - name: 1144-46N,+,1812-46N,應收５Ｇ行動電話業務收入 
            type: '[1144\-46N|1812\-46N]'
          - name: 1144-51N,+,1812-51N,應收無線電叫人業務收入 
            type: '[1144\-51N|1812\-51N]'
          - name: 1144-61N,+,1812-61N,應收數據網際網路及加值業務收入 
            type: '[1144\-61N|1812\-61N]'
          - name: 1144-62N,+,1812-62N,應收市話網際網路及加值業務收入 
            type: '[1144\-62N|1812\-62N]'
          - name: 1144-63N,+,1812-63N,應收國際網際網路及加值業務收入 
            type: '[1144\-63N|1812\-63N]'
          - name: 1144-64N,+,1812-64N,應收寬頻多媒體 MOD 業務收入 
            type: '[1144\-64N|1812\-64N]'
          - name: 1144-65N,+,1812-65N,應收寬頻多媒體業務收入 
            type: '[1144\-65N|1812\-65N]'
          - name: 1144-71N,+,1812-71N,應收衛星通信業務收入 
            type: '[1144\-71N|1812\-71N]'
          - name: 1144-81N,+,1812-81N,應收市網電路出租業務收入 
            type: '[1144\-81N|1812\-81N]'
          - name: 1144-82N,+,1812-82N,應收長網電路出租業務收入 
            type: '[1144\-82N|1812\-82N]'
          - name: 1144-83N,+,1812-83N,應收際網電路出租業務收入 
            type: '[1144\-83N|1812\-83N]'
          - name: 1144-90N,+,1812-90N,應收數據其他營業收入 
            type: '[1144\-90N|1812\-90N]'
          - name: 1144-96N,+,1812-96N,應收中文號簿廣告收入 
            type: '[1144\-96N|1812\-96N]'
          - name: 1144-97N,+,1812-97N,應收英文號簿廣告收入 
            type: '[1144\-97N|1812\-97N]'
          - name: 1144-98N,+,1812-98N,應收專標案帳款 
            type: '[1144\-98N|1812\-98N]'
          - name: 1144-99N,+,1812-99N,應收其他營業收入 
            type: '[1144\-99N|1812\-99N]'
          - name: 1144-A9N,+,1812-A9N,應收其他業務收入─行動 
            type: '[1144\-A9N|1812\-A9N]'
          - name: 1144-B9N,+,1812-B9N,應收其他業務收入─國分 
            type: '[1144\-B9N|1812\-B9N]'
          - name: 1155-01N,+,1812-95N,應收分期帳款 
            type: '[1155\-01N|1812\-95N]'
          - name: 1178-10N,+,1812-9AN,應收客戶租用設備保險費 
            type: '[1178\-10N|1812\-9AN]'
          - name: 1178-18N,+,1812-9BN,應收代收國際電信資費 
            type: '[1178\-18N|1812\-9BN]'
          - name: 1178-21N,+,1812-9CN,應收代收提供資訊服務費 
            type: '[1178\-21N|1812\-9CN]'
          - name: 1178-23N,+,1812-9DN,應收代收其他電信業者通信費 
            type: '[1178\-23N|1812\-9DN]'
          - name: 1178-25N,+,1812-9EN,應收代收其他電信或合作業者款項 
            type: '[1178\-25N|1812\-9EN]'
          - name: 1178-25H,+,1812-9EH,應收代收合作業者款項－網際網路 
            type: '[1178\-25H|1812\-9EH]'
          - name: 1178-25M,+,1812-9EM,應收台北智慧卡公司票卡儲值款 
            type: '[1178\-25M|1812\-9EM]'
          - name: 1178-26N,+,1812-9FN,應收市話業務保證金 
            type: '[1178\-26N|1812\-9FN]'
          - name: 1178-27N,+,1812-9GN,應收行動電話業務保證金 
            type: '[1178\-27N|1812\-9GN]'
          - name: 1178-29N,+,1812-9KN,應收代收ＭＯＤ業務款項 
            type: '[1178\-29N|1812\-9KN]'
          - name: 1178-30N,+,1812-9PN,應收代收停車費－行通 
            type: '[1178\-30N|1812\-9PN]'
          - name: 1178-32N,+,1812-9RN,應收市網電子商務合作業者款 
            type: '[1178\-32N|1812\-9RN]'
          - name: 1178-33N,+,1812-9SN,應收代收停車費－北區 
            type: '[1178\-33N|1812\-9SN]'
          - name: 1178-34N,+,1812-9TN,應收國際網路電子商務合作業者款 
            type: '[1178\-34N|1812\-9TN]'
          - name: 1178-35N,+,1812-9UN,應收受託代銷市網電子商務款 
            type: '[1178\-35N|1812\-9UN]'
          - name: 1178-36N,+,1812-9VN,應收受託代銷行動電話電子商務款 
            type: '[1178\-36N|1812\-9VN]'
          - name: 1178-37N,+,1812-9XN,應收受託代銷 HINET  電子商務款 
            type: '[1178\-37N|1812\-9XN]'
          - name: 1178-38N,+,1812-9YN,應收受託代銷企業客戶ＰＯＣ專案 
            type: '[1178\-38N|1812\-9YN]'
          - name: 1178-39N,+,1812-9ZN,其他應收款－應收受託代銷款 
            type: '[1178\-39N|1812\-9ZN]'
          - name: 1178-40N,,,應收代收ＯＴＴ業務款項
            type: 1178\-40N
          - name: 1178-40M,+,1812-99M,應收代收ＯＴＴ業務款項－行動 
            type: '[1178\-40M|1812\-99M]'
          - name: 1178-40H,+,1812-99H,應收代收ＯＴＴ業務款項－數據 
            type: '[1178\-40H|1812\-99H]'
          - name: 1178-41N,,,應收其它業務保證金－雲端 SAAS
            type: 1178\-41N
          - name: 1178-66N,+,1812-66N,應收中華支付平台款項－行動電話 
            type: '[1178\-66N|1812\-66N]'
          - name: 1178-67N,+,1812-67N,華支付平台款項－ HINET 
            type: '[1178\-67N|1812\-67N]'
          - name: 1178-68N,+,1812-68N,應收中華支付平台款項－市網 
            type: '[1178\-68N|1812\-68N]'
          - name: 1178-69N,+,1812-69N,應收代收 GOOGLE   公司款項 
            type: '[1178\-69N|1812\-69N]'
          - name: 1178-70N,+,1812-70N,應收代收 NETFLIX  公司款項 
            type: '[1178\-70N|1812\-70N]'
          - name: 1178-73N,+,1812-73N,應收代收 APPLE    公司款項 
            type: '[1178\-73N|1812\-73N]'
          - name: 1178-74N,+,1812-74N,應收代收 NETFLIX  公司款項 
            type: '[1178\-74N|1812\-74N]'
          - name: 1178-84N,+,1812-84N,應收ＭＯＤ業務違章費－收據類 
            type: '[1178\-84N|1812\-84N]'
          - name: 1178-85N,+,1812-85N,應收ＭＯＤ業務賠償費－收據類 
            type: '[1178\-85N|1812\-85N]'
          - name: 1178-86N,+,1812-86N,應收ＫＯＤ業務違章費－發票類 
            type: '[1178\-86N|1812\-86N]'
          - name: 1178-87N,+,1812-87N,應收ＫＯＤ業務賠償費－發票類 
            type: '[1178\-87N|1812\-87N]'
          - name: 1178-88N,+,1812-88N,應收其他營業違章費－發票類 
            type: '[1178\-88N|1812\-88N]'
          - name: 1178-88H,+,1812-88H,應收其他營業違章費－發票類 
            type: '[1178\-88H|1812\-88H]'
          - name: 1178-89N,+,1812-89N,應收其他營業賠償費－發票類 
            type: '[1178\-89N|1812\-89N]'
          - name: 1178-89H,+,1812-89H,應收其他營業賠償費－發票類 
            type: '[1178\-89H|1812\-89H]'
          - name: 1178-91N,+,1812-9WN,應收 FTTX 業務違章費 
            type: '[1178\-91N|1812\-9WN]'
          - name: 1178-92N,+,1812-9QN,應收３Ｇ行動電話業務賠償費 
            type: '[1178\-92N|1812\-9QN]'
          - name: 1178-93N,+,1812-9NN,應收其他營業外收入款項 
            type: '[1178\-93N|1812\-9NN]'
          - name: 1178-94N,+,1812-9LN,應收ＭＯＤ業務違章費－發票類 
            type: '[1178\-94N|1812\-9LN]'
          - name: 1178-95N,+,1812-9MN,應收ＭＯＤ業務賠償費－發票類 
            type: '[1178\-95N|1812\-9MN]'
          - name: 1178-96N,+,1812-9HN,應收ＡＤＳＬ業務賠償費 
            type: '[1178\-96N|1812\-9HN]'
          - name: 1178-97N,+,1812-9IN,應收市話網路業務賠償費 
            type: '[1178\-97N|1812\-9IN]'
          - name: 1178-98N,+,1812-9JN,應收ＧＳＭ行動電話業務賠償費 
            type: '[1178\-98N|1812\-9JN]'
          - name: 1178-A1N,+,1812-A1N,應收４Ｇ行動電話業務賠償費 
            type: '[1178\-A1N|1812\-A1N]'
          - name: 1178-A2N,+,1812-A2N,應收５Ｇ行動電話業務賠償費 
            type: '[1178\-A2N|1812\-A2N]'
          - name: 1178-B1N,+,1812-B1N,應收寬頻業務贈品收回款 
            type: '[1178\-B1N|1812\-B1N]'
          - name: 1178-75N,+,1812-75N,應收代收 NETFLIX 公司款項 HINET 
            type: '[1178\-75N|1812\-75N]'
          - name: 1144-31I,+,1812-31I,應收國際網路業務收入－國際 
            type: '[1144\-31I|1812\-31I]'
          - name: 1178-93H,+,1812-9NH,電子領標費用業外收入 
            type: '[1178\-93H|1812\-9NH]'
          - name: 1178-71N,+,1812-79N,應收代收 SONY 公司款項 
            type: '[1178\-71N|1812\-79N]'